# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "fedora" do |trusty|
    trusty.vm.box = "bento/fedora-32"
    trusty.vm.hostname = "fedora"

    trusty.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
      ansible.become = true
    end
  end

  config.vm.define "xenial" do |xenial|
    xenial.vm.box = "bento/ubuntu-16.04"
    xenial.vm.hostname = "xenial64"

    xenial.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
      ansible.become = true
    end
  end
end
