# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.define "trusty" do |trusty|
    trusty.vm.box = "ubuntu/trusty64"
    trusty.vm.hostname = "trusty64"

    trusty.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
      ansible.sudo = true
    end
  end

  config.vm.define "xenial" do |xenial|
    xenial.vm.box = "ubuntu/xenial64"
    xenial.vm.hostname = "xenial64"

    xenial.vm.provision "ansible" do |ansible|
      ansible.playbook = "site.yml"
      ansible.sudo = true
    end
  end
end
